name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Playwright Service
  playwright-service-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './apps/playwright-service'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Playwright Service Image'
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/firecrawl-playwright:latest
          docker push ghcr.io/${{github.actor}}/firecrawl-playwright:latest
  
  # API & Worker       
  api-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './apps/api'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build the API Image'
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/firecrawl:latest
          docker push ghcr.io/${{github.actor}}/firecrawl:latest